/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IQuestChain,
  IQuestChainInterface,
} from "../../../contracts/interfaces/IQuestChain";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "details",
        type: "string",
      },
    ],
    name: "QuestChainCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "editor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "details",
        type: "string",
      },
    ],
    name: "QuestChainEdited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "tokenURI",
        type: "string",
      },
    ],
    name: "QuestChainTokenURIUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "details",
        type: "string",
      },
    ],
    name: "QuestCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "editor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "details",
        type: "string",
      },
    ],
    name: "QuestEdited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "editor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
    ],
    name: "QuestPaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "reviewer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "quester",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "success",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "string",
        name: "details",
        type: "string",
      },
    ],
    name: "QuestProofReviewed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "quester",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "proof",
        type: "string",
      },
    ],
    name: "QuestProofSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "editor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "questId",
        type: "uint256",
      },
    ],
    name: "QuestUnpaused",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_quester",
        type: "address",
      },
    ],
    name: "burnToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_details",
        type: "string",
      },
    ],
    name: "createQuest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_details",
        type: "string",
      },
    ],
    name: "edit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_questId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_details",
        type: "string",
      },
    ],
    name: "editQuest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "string",
        name: "_details",
        type: "string",
      },
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "string",
        name: "_details",
        type: "string",
      },
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
      {
        internalType: "address[]",
        name: "_admins",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "_editors",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "_reviewers",
        type: "address[]",
      },
    ],
    name: "initWithRoles",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_quester",
        type: "address",
      },
    ],
    name: "mintToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "questChainFactory",
    outputs: [
      {
        internalType: "contract IQuestChainFactory",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "questChainId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "questChainToken",
    outputs: [
      {
        internalType: "contract IQuestChainToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_quester",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_questId",
        type: "uint256",
      },
    ],
    name: "questStatus",
    outputs: [
      {
        internalType: "enum IQuestChain.Status",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_quester",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_questId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_success",
        type: "bool",
      },
      {
        internalType: "string",
        name: "_details",
        type: "string",
      },
    ],
    name: "reviewProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
    ],
    name: "setTokenURI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_questId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_proof",
        type: "string",
      },
    ],
    name: "submitProof",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IQuestChain__factory {
  static readonly abi = _abi;
  static createInterface(): IQuestChainInterface {
    return new utils.Interface(_abi) as IQuestChainInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IQuestChain {
    return new Contract(address, _abi, signerOrProvider) as IQuestChain;
  }
}
