// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
// Auto-generated by: https://github.com/pmndrs/gltfjsx

import { useGLTF } from '@react-three/drei';
import { useThree } from '@react-three/fiber';
import React, { useRef } from 'react';

export default function Model() {
  const ref = useRef();
  const { nodes, materials } = useGLTF('/models/nft%20qc.gltf');

  useThree(({ camera }) => {
    camera.position.set(-0.5, 2, 35.5);
  });

  return (
    <group
      ref={ref}
      dispose={null}
      // rotation={[-0.65, 0.75, 0.75]}
      position={[-9, -23, 0]}
    >
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials['Material.004']}
        position={[8.9, 24.68, 4.01]}
        rotation={[0.2, -0.19, 0.9]}
        scale={2.47}
      />
      <mesh
        geometry={nodes.Curve001.geometry}
        material={materials['Material.013']}
        position={[6.33, 19.51, 2.37]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={148.79}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={materials['Material.019']}
        position={[6.31, 19.5, 2.24]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={152.86}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={materials['Material.017']}
        position={[7.82, 19.5, 2.24]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={152.86}
      />
      <mesh
        geometry={nodes.Curve006.geometry}
        material={materials['Material.010']}
        position={[7.84, 19.51, 2.37]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={148.79}
      />
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials.SVGMat}
        position={[0, 14.63, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={127.17}
      />
      <mesh
        geometry={nodes.Curve007.geometry}
        material={materials.lines}
        position={[4.3, 17.67, 2.25]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={117.34}
      />
      <mesh
        geometry={nodes.Curve004.geometry}
        material={materials['Material.020']}
        position={[4.84, 19.5, 2.24]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={152.86}
      />
      <mesh
        geometry={nodes.Curve005.geometry}
        material={materials['Material.007']}
        position={[4.86, 19.51, 2.37]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={148.79}
      />
    </group>
  );
}

useGLTF.preload('/models/nft%20qc.gltf');
// useGLTF.preload('/models/Quest%20Chains%20Token.gltf');
