/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IQuestChain,
  IQuestChainInterface,
} from "../../../contracts/interfaces/IQuestChain";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "editor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "details",
        type: "string",
      },
    ],
    name: "QuestChainEdited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "details",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string[]",
        name: "quests",
        type: "string[]",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "paused",
        type: "bool",
      },
    ],
    name: "QuestChainInit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "tokenURI",
        type: "string",
      },
    ],
    name: "QuestChainTokenURIUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "reviewer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "questerList",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "questIdList",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "bool[]",
        name: "successList",
        type: "bool[]",
      },
      {
        indexed: false,
        internalType: "string[]",
        name: "detailsList",
        type: "string[]",
      },
    ],
    name: "QuestProofsReviewed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "quester",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "questIdList",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "string[]",
        name: "proofList",
        type: "string[]",
      },
    ],
    name: "QuestProofsSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "questIdList",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "string[]",
        name: "detailsList",
        type: "string[]",
      },
    ],
    name: "QuestsCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "editor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "questIdList",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "string[]",
        name: "detailsList",
        type: "string[]",
      },
    ],
    name: "QuestsEdited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "editor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "questIdList",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "bool[]",
        name: "pausedList",
        type: "bool[]",
      },
    ],
    name: "QuestsPaused",
    type: "event",
  },
  {
    inputs: [],
    name: "burnToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string[]",
        name: "_detailsList",
        type: "string[]",
      },
    ],
    name: "createQuests",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_details",
        type: "string",
      },
    ],
    name: "edit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_questidlist",
        type: "uint256[]",
      },
      {
        internalType: "string[]",
        name: "_detailslist",
        type: "string[]",
      },
    ],
    name: "editQuests",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address[]",
            name: "owners",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "admins",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "editors",
            type: "address[]",
          },
          {
            internalType: "address[]",
            name: "reviewers",
            type: "address[]",
          },
          {
            internalType: "string[]",
            name: "quests",
            type: "string[]",
          },
          {
            internalType: "bool",
            name: "paused",
            type: "bool",
          },
          {
            internalType: "string",
            name: "details",
            type: "string",
          },
          {
            internalType: "string",
            name: "tokenURI",
            type: "string",
          },
        ],
        internalType: "struct QuestChainCommons.QuestChainInfo",
        name: "_info",
        type: "tuple",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "mintToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_questidlist",
        type: "uint256[]",
      },
      {
        internalType: "bool[]",
        name: "_pausedlist",
        type: "bool[]",
      },
    ],
    name: "pauseQuests",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "questChainFactory",
    outputs: [
      {
        internalType: "contract IQuestChainFactory",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "questChainId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "questChainToken",
    outputs: [
      {
        internalType: "contract IQuestChainToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_quester",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_questId",
        type: "uint256",
      },
    ],
    name: "questStatus",
    outputs: [
      {
        internalType: "enum IQuestChain.Status",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_questerList",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_questIdList",
        type: "uint256[]",
      },
      {
        internalType: "bool[]",
        name: "_successList",
        type: "bool[]",
      },
      {
        internalType: "string[]",
        name: "_detailsList",
        type: "string[]",
      },
    ],
    name: "reviewProofs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
    ],
    name: "setTokenURI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_questIdList",
        type: "uint256[]",
      },
      {
        internalType: "string[]",
        name: "_proofList",
        type: "string[]",
      },
    ],
    name: "submitProofs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "upgrade",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IQuestChain__factory {
  static readonly abi = _abi;
  static createInterface(): IQuestChainInterface {
    return new utils.Interface(_abi) as IQuestChainInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IQuestChain {
    return new Contract(address, _abi, signerOrProvider) as IQuestChain;
  }
}
