/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace QuestChainCommons {
  export type QuestChainInfoStruct = {
    owners: PromiseOrValue<string>[];
    admins: PromiseOrValue<string>[];
    editors: PromiseOrValue<string>[];
    reviewers: PromiseOrValue<string>[];
    quests: PromiseOrValue<string>[];
    paused: PromiseOrValue<boolean>;
    details: PromiseOrValue<string>;
    tokenURI: PromiseOrValue<string>;
  };

  export type QuestChainInfoStructOutput = [
    string[],
    string[],
    string[],
    string[],
    string[],
    boolean,
    string,
    string
  ] & {
    owners: string[];
    admins: string[];
    editors: string[];
    reviewers: string[];
    quests: string[];
    paused: boolean;
    details: string;
    tokenURI: string;
  };
}

export interface IQuestChainInterface extends utils.Interface {
  functions: {
    "burnToken()": FunctionFragment;
    "createQuests(string[])": FunctionFragment;
    "edit(string)": FunctionFragment;
    "editQuests(uint256[],string[])": FunctionFragment;
    "getTokenURI()": FunctionFragment;
    "init((address[],address[],address[],address[],string[],bool,string,string))": FunctionFragment;
    "mintToken()": FunctionFragment;
    "pauseQuests(uint256[],bool[])": FunctionFragment;
    "questChainFactory()": FunctionFragment;
    "questChainId()": FunctionFragment;
    "questChainToken()": FunctionFragment;
    "questStatus(address,uint256)": FunctionFragment;
    "reviewProofs(address[],uint256[],bool[],string[])": FunctionFragment;
    "setTokenURI(string)": FunctionFragment;
    "submitProofs(uint256[],string[])": FunctionFragment;
    "upgrade()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "burnToken"
      | "createQuests"
      | "edit"
      | "editQuests"
      | "getTokenURI"
      | "init"
      | "mintToken"
      | "pauseQuests"
      | "questChainFactory"
      | "questChainId"
      | "questChainToken"
      | "questStatus"
      | "reviewProofs"
      | "setTokenURI"
      | "submitProofs"
      | "upgrade"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "burnToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createQuests",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "edit",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "editQuests",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [QuestChainCommons.QuestChainInfoStruct]
  ): string;
  encodeFunctionData(functionFragment: "mintToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseQuests",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<boolean>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "questChainFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "questChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "questChainToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "questStatus",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "reviewProofs",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<boolean>[],
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenURI",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProofs",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(functionFragment: "upgrade", values?: undefined): string;

  decodeFunctionResult(functionFragment: "burnToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createQuests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "edit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "editQuests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseQuests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "questChainFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "questChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "questChainToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "questStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reviewProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProofs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;

  events: {
    "QuestChainEdited(address,string)": EventFragment;
    "QuestChainInit(string,string[],bool)": EventFragment;
    "QuestChainTokenURIUpdated(string)": EventFragment;
    "QuestProofsReviewed(address,address[],uint256[],bool[],string[])": EventFragment;
    "QuestProofsSubmitted(address,uint256[],string[])": EventFragment;
    "QuestsCreated(address,uint256[],string[])": EventFragment;
    "QuestsEdited(address,uint256[],string[])": EventFragment;
    "QuestsPaused(address,uint256[],bool[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "QuestChainEdited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QuestChainInit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QuestChainTokenURIUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QuestProofsReviewed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QuestProofsSubmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QuestsCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QuestsEdited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QuestsPaused"): EventFragment;
}

export interface QuestChainEditedEventObject {
  editor: string;
  details: string;
}
export type QuestChainEditedEvent = TypedEvent<
  [string, string],
  QuestChainEditedEventObject
>;

export type QuestChainEditedEventFilter =
  TypedEventFilter<QuestChainEditedEvent>;

export interface QuestChainInitEventObject {
  details: string;
  quests: string[];
  paused: boolean;
}
export type QuestChainInitEvent = TypedEvent<
  [string, string[], boolean],
  QuestChainInitEventObject
>;

export type QuestChainInitEventFilter = TypedEventFilter<QuestChainInitEvent>;

export interface QuestChainTokenURIUpdatedEventObject {
  tokenURI: string;
}
export type QuestChainTokenURIUpdatedEvent = TypedEvent<
  [string],
  QuestChainTokenURIUpdatedEventObject
>;

export type QuestChainTokenURIUpdatedEventFilter =
  TypedEventFilter<QuestChainTokenURIUpdatedEvent>;

export interface QuestProofsReviewedEventObject {
  reviewer: string;
  questerList: string[];
  questIdList: BigNumber[];
  successList: boolean[];
  detailsList: string[];
}
export type QuestProofsReviewedEvent = TypedEvent<
  [string, string[], BigNumber[], boolean[], string[]],
  QuestProofsReviewedEventObject
>;

export type QuestProofsReviewedEventFilter =
  TypedEventFilter<QuestProofsReviewedEvent>;

export interface QuestProofsSubmittedEventObject {
  quester: string;
  questIdList: BigNumber[];
  proofList: string[];
}
export type QuestProofsSubmittedEvent = TypedEvent<
  [string, BigNumber[], string[]],
  QuestProofsSubmittedEventObject
>;

export type QuestProofsSubmittedEventFilter =
  TypedEventFilter<QuestProofsSubmittedEvent>;

export interface QuestsCreatedEventObject {
  creator: string;
  questIdList: BigNumber[];
  detailsList: string[];
}
export type QuestsCreatedEvent = TypedEvent<
  [string, BigNumber[], string[]],
  QuestsCreatedEventObject
>;

export type QuestsCreatedEventFilter = TypedEventFilter<QuestsCreatedEvent>;

export interface QuestsEditedEventObject {
  editor: string;
  questIdList: BigNumber[];
  detailsList: string[];
}
export type QuestsEditedEvent = TypedEvent<
  [string, BigNumber[], string[]],
  QuestsEditedEventObject
>;

export type QuestsEditedEventFilter = TypedEventFilter<QuestsEditedEvent>;

export interface QuestsPausedEventObject {
  editor: string;
  questIdList: BigNumber[];
  pausedList: boolean[];
}
export type QuestsPausedEvent = TypedEvent<
  [string, BigNumber[], boolean[]],
  QuestsPausedEventObject
>;

export type QuestsPausedEventFilter = TypedEventFilter<QuestsPausedEvent>;

export interface IQuestChain extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IQuestChainInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    burnToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createQuests(
      _detailsList: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    edit(
      _details: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    editQuests(
      _questidlist: PromiseOrValue<BigNumberish>[],
      _detailslist: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getTokenURI(overrides?: CallOverrides): Promise<[string]>;

    init(
      _info: QuestChainCommons.QuestChainInfoStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mintToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pauseQuests(
      _questidlist: PromiseOrValue<BigNumberish>[],
      _pausedlist: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    questChainFactory(overrides?: CallOverrides): Promise<[string]>;

    questChainId(overrides?: CallOverrides): Promise<[BigNumber]>;

    questChainToken(overrides?: CallOverrides): Promise<[string]>;

    questStatus(
      _quester: PromiseOrValue<string>,
      _questId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    reviewProofs(
      _questerList: PromiseOrValue<string>[],
      _questIdList: PromiseOrValue<BigNumberish>[],
      _successList: PromiseOrValue<boolean>[],
      _detailsList: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTokenURI(
      _tokenURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitProofs(
      _questIdList: PromiseOrValue<BigNumberish>[],
      _proofList: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgrade(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  burnToken(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createQuests(
    _detailsList: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  edit(
    _details: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  editQuests(
    _questidlist: PromiseOrValue<BigNumberish>[],
    _detailslist: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getTokenURI(overrides?: CallOverrides): Promise<string>;

  init(
    _info: QuestChainCommons.QuestChainInfoStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mintToken(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pauseQuests(
    _questidlist: PromiseOrValue<BigNumberish>[],
    _pausedlist: PromiseOrValue<boolean>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  questChainFactory(overrides?: CallOverrides): Promise<string>;

  questChainId(overrides?: CallOverrides): Promise<BigNumber>;

  questChainToken(overrides?: CallOverrides): Promise<string>;

  questStatus(
    _quester: PromiseOrValue<string>,
    _questId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  reviewProofs(
    _questerList: PromiseOrValue<string>[],
    _questIdList: PromiseOrValue<BigNumberish>[],
    _successList: PromiseOrValue<boolean>[],
    _detailsList: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTokenURI(
    _tokenURI: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitProofs(
    _questIdList: PromiseOrValue<BigNumberish>[],
    _proofList: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgrade(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    burnToken(overrides?: CallOverrides): Promise<void>;

    createQuests(
      _detailsList: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    edit(
      _details: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    editQuests(
      _questidlist: PromiseOrValue<BigNumberish>[],
      _detailslist: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getTokenURI(overrides?: CallOverrides): Promise<string>;

    init(
      _info: QuestChainCommons.QuestChainInfoStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    mintToken(overrides?: CallOverrides): Promise<void>;

    pauseQuests(
      _questidlist: PromiseOrValue<BigNumberish>[],
      _pausedlist: PromiseOrValue<boolean>[],
      overrides?: CallOverrides
    ): Promise<void>;

    questChainFactory(overrides?: CallOverrides): Promise<string>;

    questChainId(overrides?: CallOverrides): Promise<BigNumber>;

    questChainToken(overrides?: CallOverrides): Promise<string>;

    questStatus(
      _quester: PromiseOrValue<string>,
      _questId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    reviewProofs(
      _questerList: PromiseOrValue<string>[],
      _questIdList: PromiseOrValue<BigNumberish>[],
      _successList: PromiseOrValue<boolean>[],
      _detailsList: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenURI(
      _tokenURI: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    submitProofs(
      _questIdList: PromiseOrValue<BigNumberish>[],
      _proofList: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    upgrade(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "QuestChainEdited(address,string)"(
      editor?: null,
      details?: null
    ): QuestChainEditedEventFilter;
    QuestChainEdited(
      editor?: null,
      details?: null
    ): QuestChainEditedEventFilter;

    "QuestChainInit(string,string[],bool)"(
      details?: null,
      quests?: null,
      paused?: null
    ): QuestChainInitEventFilter;
    QuestChainInit(
      details?: null,
      quests?: null,
      paused?: null
    ): QuestChainInitEventFilter;

    "QuestChainTokenURIUpdated(string)"(
      tokenURI?: null
    ): QuestChainTokenURIUpdatedEventFilter;
    QuestChainTokenURIUpdated(
      tokenURI?: null
    ): QuestChainTokenURIUpdatedEventFilter;

    "QuestProofsReviewed(address,address[],uint256[],bool[],string[])"(
      reviewer?: null,
      questerList?: null,
      questIdList?: null,
      successList?: null,
      detailsList?: null
    ): QuestProofsReviewedEventFilter;
    QuestProofsReviewed(
      reviewer?: null,
      questerList?: null,
      questIdList?: null,
      successList?: null,
      detailsList?: null
    ): QuestProofsReviewedEventFilter;

    "QuestProofsSubmitted(address,uint256[],string[])"(
      quester?: null,
      questIdList?: null,
      proofList?: null
    ): QuestProofsSubmittedEventFilter;
    QuestProofsSubmitted(
      quester?: null,
      questIdList?: null,
      proofList?: null
    ): QuestProofsSubmittedEventFilter;

    "QuestsCreated(address,uint256[],string[])"(
      creator?: null,
      questIdList?: null,
      detailsList?: null
    ): QuestsCreatedEventFilter;
    QuestsCreated(
      creator?: null,
      questIdList?: null,
      detailsList?: null
    ): QuestsCreatedEventFilter;

    "QuestsEdited(address,uint256[],string[])"(
      editor?: null,
      questIdList?: null,
      detailsList?: null
    ): QuestsEditedEventFilter;
    QuestsEdited(
      editor?: null,
      questIdList?: null,
      detailsList?: null
    ): QuestsEditedEventFilter;

    "QuestsPaused(address,uint256[],bool[])"(
      editor?: null,
      questIdList?: null,
      pausedList?: null
    ): QuestsPausedEventFilter;
    QuestsPaused(
      editor?: null,
      questIdList?: null,
      pausedList?: null
    ): QuestsPausedEventFilter;
  };

  estimateGas: {
    burnToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createQuests(
      _detailsList: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    edit(
      _details: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    editQuests(
      _questidlist: PromiseOrValue<BigNumberish>[],
      _detailslist: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getTokenURI(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      _info: QuestChainCommons.QuestChainInfoStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mintToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pauseQuests(
      _questidlist: PromiseOrValue<BigNumberish>[],
      _pausedlist: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    questChainFactory(overrides?: CallOverrides): Promise<BigNumber>;

    questChainId(overrides?: CallOverrides): Promise<BigNumber>;

    questChainToken(overrides?: CallOverrides): Promise<BigNumber>;

    questStatus(
      _quester: PromiseOrValue<string>,
      _questId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reviewProofs(
      _questerList: PromiseOrValue<string>[],
      _questIdList: PromiseOrValue<BigNumberish>[],
      _successList: PromiseOrValue<boolean>[],
      _detailsList: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTokenURI(
      _tokenURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitProofs(
      _questIdList: PromiseOrValue<BigNumberish>[],
      _proofList: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgrade(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burnToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createQuests(
      _detailsList: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    edit(
      _details: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    editQuests(
      _questidlist: PromiseOrValue<BigNumberish>[],
      _detailslist: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getTokenURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    init(
      _info: QuestChainCommons.QuestChainInfoStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mintToken(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pauseQuests(
      _questidlist: PromiseOrValue<BigNumberish>[],
      _pausedlist: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    questChainFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    questChainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    questChainToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    questStatus(
      _quester: PromiseOrValue<string>,
      _questId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reviewProofs(
      _questerList: PromiseOrValue<string>[],
      _questIdList: PromiseOrValue<BigNumberish>[],
      _successList: PromiseOrValue<boolean>[],
      _detailsList: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTokenURI(
      _tokenURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitProofs(
      _questIdList: PromiseOrValue<BigNumberish>[],
      _proofList: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgrade(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
